name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: read

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fix Rollup optional dependencies
        run: |
          rm -rf node_modules/@rollup/rollup-linux-x64-gnu
          npm install @rollup/rollup-linux-x64-gnu --no-save

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Reset and setup database
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/test_db'
        run: |
          npx prisma db push --force-reset
          npx prisma db seed

      - name: Sync SvelteKit
        run: npx svelte-kit sync

      - name: Lint
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

      - name: Build project
        env:
          OPENAI_API_KEY: 'dummy-key-for-ci-build'
        run: npx vite build

      - name: Run basic tests (skip fixture-dependent tests)
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/test_db'
        run: npx vitest run src/lib/__tests__/basic.spec.ts
